# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rvrgui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(712, 677)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(712, 814))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 240, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 247, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 120, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 160, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 240, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 247, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 240, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 247, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 120, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 160, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 240, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 247, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 120, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 240, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 247, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 120, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 160, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 120, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 120, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 240, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 240, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 240, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        MainWindow.setFont(font)
        icon = QtGui.QIcon.fromTheme("D:\\work\\Reamon\\Python\\rvr\\64.ico")
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.APframe = QtWidgets.QFrame(self.centralwidget)
        self.APframe.setGeometry(QtCore.QRect(0, 0, 351, 201))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.APframe.setFont(font)
        self.APframe.setFrameShape(QtWidgets.QFrame.Box)
        self.APframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.APframe.setLineWidth(1)
        self.APframe.setObjectName("APframe")
        self.label = QtWidgets.QLabel(self.APframe)
        self.label.setGeometry(QtCore.QRect(10, 0, 30, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.APframe)
        self.label_2.setGeometry(QtCore.QRect(60, 170, 111, 22))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ApType = QtWidgets.QComboBox(self.APframe)
        self.ApType.setGeometry(QtCore.QRect(170, 170, 81, 22))
        self.ApType.setObjectName("ApType")
        self.ApType.addItem("")
        self.ApType.setItemText(0, "")
        self.ApType.addItem("")
        self.ApType.addItem("")
        self.ApType.addItem("")
        self.ApType.addItem("")
        self.label_3 = QtWidgets.QLabel(self.APframe)
        self.label_3.setGeometry(QtCore.QRect(60, 20, 60, 22))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.APframe)
        self.label_4.setGeometry(QtCore.QRect(60, 50, 61, 22))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.APframe)
        self.label_5.setGeometry(QtCore.QRect(60, 80, 61, 22))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.ApIp = QtWidgets.QLineEdit(self.APframe)
        self.ApIp.setGeometry(QtCore.QRect(170, 20, 121, 22))
        self.ApIp.setObjectName("ApIp")
        self.Username = QtWidgets.QLineEdit(self.APframe)
        self.Username.setGeometry(QtCore.QRect(170, 50, 121, 22))
        self.Username.setObjectName("Username")
        self.Password = QtWidgets.QLineEdit(self.APframe)
        self.Password.setGeometry(QtCore.QRect(170, 80, 121, 22))
        self.Password.setObjectName("Password")
        self.radioButton2 = QtWidgets.QRadioButton(self.APframe)
        self.radioButton2.setGeometry(QtCore.QRect(170, 110, 60, 22))
        self.radioButton2.setObjectName("radioButton2")
        self.label_6 = QtWidgets.QLabel(self.APframe)
        self.label_6.setGeometry(QtCore.QRect(60, 110, 61, 22))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.radioButton5 = QtWidgets.QRadioButton(self.APframe)
        self.radioButton5.setGeometry(QtCore.QRect(230, 110, 60, 22))
        self.radioButton5.setObjectName("radioButton5")
        self.label_7 = QtWidgets.QLabel(self.APframe)
        self.label_7.setGeometry(QtCore.QRect(60, 140, 61, 22))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.Channel = QtWidgets.QLineEdit(self.APframe)
        self.Channel.setGeometry(QtCore.QRect(170, 140, 121, 22))
        self.Channel.setObjectName("Channel")
        self.ATTframe = QtWidgets.QFrame(self.centralwidget)
        self.ATTframe.setGeometry(QtCore.QRect(0, 370, 351, 121))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ATTframe.setFont(font)
        self.ATTframe.setFrameShape(QtWidgets.QFrame.Box)
        self.ATTframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ATTframe.setLineWidth(1)
        self.ATTframe.setObjectName("ATTframe")
        self.label_8 = QtWidgets.QLabel(self.ATTframe)
        self.label_8.setGeometry(QtCore.QRect(10, 0, 100, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.ATTframe)
        self.label_10.setGeometry(QtCore.QRect(60, 30, 50, 22))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.ATTframe)
        self.label_11.setGeometry(QtCore.QRect(240, 30, 50, 22))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.ATTframe)
        self.label_12.setGeometry(QtCore.QRect(160, 30, 50, 22))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.ATTframe)
        self.label_13.setGeometry(QtCore.QRect(60, 60, 80, 22))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.Start = QtWidgets.QLineEdit(self.ATTframe)
        self.Start.setGeometry(QtCore.QRect(110, 30, 35, 22))
        self.Start.setObjectName("Start")
        self.Step = QtWidgets.QLineEdit(self.ATTframe)
        self.Step.setGeometry(QtCore.QRect(280, 30, 35, 22))
        self.Step.setObjectName("Step")
        self.End = QtWidgets.QLineEdit(self.ATTframe)
        self.End.setGeometry(QtCore.QRect(190, 30, 35, 22))
        self.End.setObjectName("End")
        self.LineLoss = QtWidgets.QLineEdit(self.ATTframe)
        self.LineLoss.setGeometry(QtCore.QRect(140, 60, 100, 22))
        self.LineLoss.setObjectName("LineLoss")
        self.label_18 = QtWidgets.QLabel(self.ATTframe)
        self.label_18.setGeometry(QtCore.QRect(60, 90, 71, 22))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.NumberButton2_2 = QtWidgets.QRadioButton(self.ATTframe)
        self.NumberButton2_2.setGeometry(QtCore.QRect(130, 90, 31, 22))
        self.NumberButton2_2.setObjectName("NumberButton2_2")
        self.NumberButton4_4 = QtWidgets.QRadioButton(self.ATTframe)
        self.NumberButton4_4.setGeometry(QtCore.QRect(210, 90, 31, 22))
        self.NumberButton4_4.setObjectName("NumberButton4_4")
        self.NumberButton3_3 = QtWidgets.QRadioButton(self.ATTframe)
        self.NumberButton3_3.setGeometry(QtCore.QRect(170, 90, 31, 22))
        self.NumberButton3_3.setObjectName("NumberButton3_3")
        self.NumberButton8_8 = QtWidgets.QRadioButton(self.ATTframe)
        self.NumberButton8_8.setGeometry(QtCore.QRect(250, 90, 31, 22))
        self.NumberButton8_8.setObjectName("NumberButton8_8")
        self.STAframe = QtWidgets.QFrame(self.centralwidget)
        self.STAframe.setGeometry(QtCore.QRect(0, 200, 351, 171))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 240, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 247, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 120, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 160, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 240, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 247, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 240, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 247, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 120, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 160, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 240, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 247, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 120, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 240, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 247, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 120, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 160, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 120, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 120, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 240, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 240, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 240, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.STAframe.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.STAframe.setFont(font)
        self.STAframe.setFrameShape(QtWidgets.QFrame.Box)
        self.STAframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.STAframe.setLineWidth(1)
        self.STAframe.setObjectName("STAframe")
        self.label_9 = QtWidgets.QLabel(self.STAframe)
        self.label_9.setGeometry(QtCore.QRect(10, 0, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_14 = QtWidgets.QLabel(self.STAframe)
        self.label_14.setGeometry(QtCore.QRect(60, 20, 61, 22))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.STAframe)
        self.label_15.setGeometry(QtCore.QRect(60, 50, 61, 22))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.STAframe)
        self.label_16.setGeometry(QtCore.QRect(60, 110, 61, 22))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.STAframe)
        self.label_17.setGeometry(QtCore.QRect(60, 80, 91, 22))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.StaIp = QtWidgets.QLineEdit(self.STAframe)
        self.StaIp.setGeometry(QtCore.QRect(170, 50, 121, 22))
        self.StaIp.setObjectName("StaIp")
        self.Duration = QtWidgets.QLineEdit(self.STAframe)
        self.Duration.setGeometry(QtCore.QRect(170, 110, 61, 22))
        self.Duration.setObjectName("Duration")
        self.PairNumber = QtWidgets.QLineEdit(self.STAframe)
        self.PairNumber.setGeometry(QtCore.QRect(170, 80, 61, 22))
        self.PairNumber.setObjectName("PairNumber")
        self.listWidget = QtWidgets.QListWidget(self.STAframe)
        self.listWidget.setGeometry(QtCore.QRect(170, 20, 141, 21))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.label_19 = QtWidgets.QLabel(self.STAframe)
        self.label_19.setGeometry(QtCore.QRect(60, 140, 101, 22))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.textEdit = QtWidgets.QTextEdit(self.STAframe)
        self.textEdit.setGeometry(QtCore.QRect(170, 140, 141, 22))
        self.textEdit.setObjectName("textEdit")
        self.Confirm = QtWidgets.QPushButton(self.centralwidget)
        self.Confirm.setGeometry(QtCore.QRect(270, 600, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Confirm.setFont(font)
        self.Confirm.setObjectName("Confirm")
        self.Run = QtWidgets.QPushButton(self.centralwidget)
        self.Run.setGeometry(QtCore.QRect(360, 600, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Run.setFont(font)
        self.Run.setObjectName("Run")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(360, 0, 341, 591))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 586, 638))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setEnabled(False)
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.Report = QtWidgets.QPushButton(self.centralwidget)
        self.Report.setGeometry(QtCore.QRect(630, 600, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Report.setFont(font)
        self.Report.setObjectName("Report")
        self.TESTframe = QtWidgets.QFrame(self.centralwidget)
        self.TESTframe.setGeometry(QtCore.QRect(0, 540, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.TESTframe.setFont(font)
        self.TESTframe.setFrameShape(QtWidgets.QFrame.Box)
        self.TESTframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TESTframe.setLineWidth(1)
        self.TESTframe.setObjectName("TESTframe")
        self.label_22 = QtWidgets.QLabel(self.TESTframe)
        self.label_22.setGeometry(QtCore.QRect(10, 0, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.radioButton = QtWidgets.QRadioButton(self.TESTframe)
        self.radioButton.setGeometry(QtCore.QRect(60, 20, 89, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.TESTframe)
        self.radioButton_2.setGeometry(QtCore.QRect(170, 20, 89, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.TTframe = QtWidgets.QFrame(self.centralwidget)
        self.TTframe.setGeometry(QtCore.QRect(0, 490, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.TTframe.setFont(font)
        self.TTframe.setFrameShape(QtWidgets.QFrame.Box)
        self.TTframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TTframe.setLineWidth(1)
        self.TTframe.setObjectName("TTframe")
        self.compass = QtWidgets.QLabel(self.TTframe)
        self.compass.setGeometry(QtCore.QRect(10, 0, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.compass.setFont(font)
        self.compass.setObjectName("compass")
        self.Angle1 = QtWidgets.QLabel(self.TTframe)
        self.Angle1.setGeometry(QtCore.QRect(60, 20, 61, 22))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.Angle1.setFont(font)
        self.Angle1.setObjectName("Angle1")
        self.PairNumber_2 = QtWidgets.QLineEdit(self.TTframe)
        self.PairNumber_2.setGeometry(QtCore.QRect(120, 20, 61, 22))
        self.PairNumber_2.setObjectName("PairNumber_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 712, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CIG Rate over Range test tool v1.0"))
        self.label.setText(_translate("MainWindow", "AP"))
        self.label_2.setText(_translate("MainWindow", "AP config file:"))
        self.ApType.setItemText(1, _translate("MainWindow", "AP-365"))
        self.ApType.setItemText(2, _translate("MainWindow", "WF-180"))
        self.ApType.setItemText(3, _translate("MainWindow", "WF-1871"))
        self.ApType.setItemText(4, _translate("MainWindow", "WF-1821"))
        self.label_3.setText(_translate("MainWindow", "AP IP:"))
        self.label_4.setText(_translate("MainWindow", "Username:"))
        self.label_5.setText(_translate("MainWindow", "Password："))
        self.ApIp.setText(_translate("MainWindow", "192.168.1.1"))
        self.Username.setText(_translate("MainWindow", "root"))
        self.Password.setText(_translate("MainWindow", "admin"))
        self.radioButton2.setText(_translate("MainWindow", "2G"))
        self.label_6.setText(_translate("MainWindow", "Radio:"))
        self.radioButton5.setText(_translate("MainWindow", "5G"))
        self.label_7.setText(_translate("MainWindow", "Channel："))
        self.Channel.setText(_translate("MainWindow", "6"))
        self.label_8.setText(_translate("MainWindow", "ATTENUATION"))
        self.label_10.setText(_translate("MainWindow", "Start:"))
        self.label_11.setText(_translate("MainWindow", "Step："))
        self.label_12.setText(_translate("MainWindow", "End:"))
        self.label_13.setText(_translate("MainWindow", "Cable Loss:"))
        self.Start.setText(_translate("MainWindow", "0"))
        self.Step.setText(_translate("MainWindow", "5"))
        self.End.setText(_translate("MainWindow", "90"))
        self.LineLoss.setText(_translate("MainWindow", "5"))
        self.label_18.setText(_translate("MainWindow", "Number"))
        self.NumberButton2_2.setText(_translate("MainWindow", "2"))
        self.NumberButton4_4.setText(_translate("MainWindow", "4"))
        self.NumberButton3_3.setText(_translate("MainWindow", "3"))
        self.NumberButton8_8.setText(_translate("MainWindow", "8"))
        self.label_9.setText(_translate("MainWindow", "STATION"))
        self.label_14.setText(_translate("MainWindow", "STA Type:"))
        self.label_15.setText(_translate("MainWindow", "STA IP："))
        self.label_16.setText(_translate("MainWindow", "Duration："))
        self.label_17.setText(_translate("MainWindow", "Pair Number："))
        self.StaIp.setText(_translate("MainWindow", "192.168.1.100"))
        self.Duration.setText(_translate("MainWindow", "90"))
        self.PairNumber.setText(_translate("MainWindow", "4"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Wireless Card-PC"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Client-DUT"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_19.setText(_translate("MainWindow", "STA config file:"))
        self.Confirm.setText(_translate("MainWindow", "Confirm"))
        self.Run.setText(_translate("MainWindow", "Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Log Window"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.Report.setText(_translate("MainWindow", "Report"))
        self.label_22.setText(_translate("MainWindow", "TEST TYPE"))
        self.radioButton.setText(_translate("MainWindow", "Continue"))
        self.radioButton_2.setText(_translate("MainWindow", "Restart"))
        self.compass.setText(_translate("MainWindow", "TURNTABLE"))
        self.Angle1.setText(_translate("MainWindow", "Angles:"))
        self.PairNumber_2.setText(_translate("MainWindow", "4"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

